"""add s3_key to invoices

Revision ID: 4db7ad574ec1
Revises: 95215856a31c
Create Date: 2026-08-22 13:11:51.272487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db7ad574ec1'
down_revision: Union[str, Sequence[str], None] = '95215856a31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 's3_key')
    # ### end Alembic commands ###
